[colors.primary]
background = "#1F2023"

[cursor]
blink_interval = 500
blink_timeout = 0
unfocused_hollow = true

[cursor.style]
blinking = "On"

[env]
TERM = "xterm-256color"

[font]
size = 17

[font.offset]
y = 3

[font.glyph_offset]
y = 1

[font.bold]
family = "BerkeleyMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BerkeleyMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "BerkeleyMono Nerd Font"
style = "Regular Italic"

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/opt/homebrew/bin/fish"

[window]
blur = true
decorations = "Buttonless"
dynamic_padding = false
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
# opacity = 0.95

[terminal]
