# Set true color
set-option -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0


# Enable mouse support
set -g mouse on

# Set prefix key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Set vi-mode
set-window-option -g mode-keys vi

# Set repeat time
set-option -g repeat-time 2000

# Resize-pane
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2 
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Toogle status bar
bind m set-option -g status

# Popup keybindings
bind j display-popup -w80% -h80% -d "#{pane_current_path}" -E

# Cycle panes while zoomed in
bind -r a select-pane -t .+1 \;  resize-pane -Z

# Yank keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle 
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel 

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Switch windows shortcuts
bind -n M-H previous-window
bind -n M-L next-window

# Start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'odedlaz/tmux-onedark-theme'

# Transparent background
set -g status-style bg=default

# Set position to top
set-option -g status-position bottom 

# Set fish as the default shell
set -g default-command /opt/homebrew/bin/fish
set -g default-shell /opt/homebrew/bin/fish

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
